import sqlite3
import os
import csv

os.makedirs('data', exist_ok=True)

conn = sqlite3.connect('data/keywords.db')
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS io_access (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        access_name TEXT NOT NULL,
        application TEXT,
        topic TEXT,
        advise_active TEXT,
        dde_protocol TEXT,
        sec_application TEXT,
        sec_topic TEXT,
        sec_advise_active TEXT,
        sec_dde_protocol TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS io_disc (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tag_name TEXT NOT NULL,
        group_name TEXT,
        comment TEXT,
        logged TEXT,
        event_logged TEXT,
        event_logging_priority INTEGER,
        retentive_value TEXT,
        initial_disc TEXT,
        off_msg TEXT,
        on_msg TEXT,
        alarm_state TEXT,
        alarm_pri INTEGER,
        d_conversion TEXT,
        access_name TEXT,
        item_use_tagname TEXT,
        item_name TEXT,
        read_only TEXT,
        alarm_comment TEXT,
        alarm_ack_model INTEGER,
        dsc_alarm_disable INTEGER,
        dsc_alarm_inhibitor INTEGER,
        symbolic_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS io_int (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tag_name TEXT NOT NULL,
        group_name TEXT,
        comment TEXT,
        logged TEXT,
        event_logged TEXT,
        event_logging_priority INTEGER,
        retentive_value TEXT,
        retentive_alarm_parameters TEXT,
        alarm_value_deadband REAL,
        alarm_dev_deadband REAL,
        eng_units TEXT,
        initial_value REAL,
        min_value REAL,
        max_value REAL,
        deadband REAL,
        log_deadband REAL,
        lolo_alarm_state TEXT,
        lolo_alarm_value REAL,
        lolo_alarm_pri INTEGER,
        lo_alarm_state TEXT,
        lo_alarm_value REAL,
        lo_alarm_pri INTEGER,
        hi_alarm_state TEXT,
        hi_alarm_value REAL,
        hi_alarm_pri INTEGER,
        hihi_alarm_state TEXT,
        hihi_alarm_value REAL,
        hihi_alarm_pri INTEGER,
        minor_dev_alarm_state TEXT,
        minor_dev_alarm_value REAL,
        minor_dev_alarm_pri INTEGER,
        major_dev_alarm_state TEXT,
        major_dev_alarm_value REAL,
        major_dev_alarm_pri INTEGER,
        dev_target TEXT,
        roc_alarm_state TEXT,
        roc_alarm_value REAL,
        roc_alarm_pri INTEGER,
        roc_time_base TEXT,
        min_raw INTEGER,
        max_raw INTEGER,
        conversion TEXT,
        access_name TEXT,
        item_use_tagname TEXT,
        item_name TEXT,
        read_only TEXT,
        alarm_comment TEXT,
        alarm_ack_model INTEGER,
        lolo_alarm_disable INTEGER,
        lo_alarm_disable INTEGER,
        hi_alarm_disable INTEGER,
        hihi_alarm_disable INTEGER,
        min_dev_alarm_disable INTEGER,
        maj_dev_alarm_disable INTEGER,
        roc_alarm_disable INTEGER,
        lolo_alarm_inhibitor TEXT,
        lo_alarm_inhibitor TEXT,
        hi_alarm_inhibitor TEXT,
        hihi_alarm_inhibitor TEXT,
        min_dev_alarm_inhibitor TEXT,
        maj_dev_alarm_inhibitor TEXT,
        roc_alarm_inhibitor TEXT,
        symbolic_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS io_real (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tag_name TEXT NOT NULL,
        group_name TEXT,
        comment TEXT,
        logged TEXT,
        event_logged TEXT,
        event_logging_priority INTEGER,
        retentive_value TEXT,
        retentive_alarm_parameters TEXT,
        alarm_value_deadband REAL,
        alarm_dev_deadband REAL,
        eng_units TEXT,
        initial_value REAL,
        min_eu REAL,
        max_eu REAL,
        deadband REAL,
        log_deadband REAL,
        lolo_alarm_state TEXT,
        lolo_alarm_value REAL,
        lolo_alarm_pri INTEGER,
        lo_alarm_state TEXT,
        lo_alarm_value REAL,
        lo_alarm_pri INTEGER,
        hi_alarm_state TEXT,
        hi_alarm_value REAL,
        hi_alarm_pri INTEGER,
        hihi_alarm_state TEXT,
        hihi_alarm_value REAL,
        hihi_alarm_pri INTEGER,
        minor_dev_alarm_state TEXT,
        minor_dev_alarm_value REAL,
        minor_dev_alarm_pri INTEGER,
        major_dev_alarm_state TEXT,
        major_dev_alarm_value REAL,
        major_dev_alarm_pri INTEGER,
        dev_target TEXT,
        roc_alarm_state TEXT,
        roc_alarm_value REAL,
        roc_alarm_pri INTEGER,
        roc_time_base TEXT,
        min_raw INTEGER,
        max_raw INTEGER,
        conversion TEXT,
        access_name TEXT,
        item_use_tagname TEXT,
        item_name TEXT,
        read_only TEXT,
        alarm_comment TEXT,
        alarm_ack_model INTEGER,
        lolo_alarm_disable INTEGER,
        lo_alarm_disable INTEGER,
        hi_alarm_disable INTEGER,
        hihi_alarm_disable INTEGER,
        min_dev_alarm_disable INTEGER,
        maj_dev_alarm_disable INTEGER,
        roc_alarm_disable INTEGER,
        lolo_alarm_inhibitor TEXT,
        lo_alarm_inhibitor TEXT,
        hi_alarm_inhibitor TEXT,
        hihi_alarm_inhibitor TEXT,
        min_dev_alarm_inhibitor TEXT,
        maj_dev_alarm_inhibitor TEXT,
        roc_alarm_inhibitor TEXT,
        symbolic_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS memory_disc (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tag_name TEXT NOT NULL,
        group_name TEXT,
        comment TEXT,
        logged TEXT,
        event_logged TEXT,
        event_logging_priority INTEGER,
        retentive_value TEXT,
        initial_disc TEXT,
        off_msg TEXT,
        on_msg TEXT,
        alarm_state TEXT,
        alarm_pri INTEGER,
        alarm_comment TEXT,
        alarm_ack_model INTEGER,
        dsc_alarm_disable INTEGER,
        dsc_alarm_inhibitor INTEGER,
        symbolic_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS memory_real (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tag_name TEXT NOT NULL,
        group_name TEXT,
        comment TEXT,
        logged TEXT,
        event_logged TEXT,
        event_logging_priority INTEGER,
        retentive_value TEXT,
        retentive_alarm_parameters TEXT,
        alarm_value_deadband REAL,
        alarm_dev_deadband REAL,
        eng_units TEXT,
        initial_value REAL,
        min_value REAL,
        max_value REAL,
        deadband REAL,
        log_deadband REAL,
        lolo_alarm_state TEXT,
        lolo_alarm_value REAL,
        lolo_alarm_pri INTEGER,
        lo_alarm_state TEXT,
        lo_alarm_value REAL,
        lo_alarm_pri INTEGER,
        hi_alarm_state TEXT,
        hi_alarm_value REAL,
        hi_alarm_pri INTEGER,
        hihi_alarm_state TEXT,
        hihi_alarm_value REAL,
        hihi_alarm_pri INTEGER,
        minor_dev_alarm_state TEXT,
        minor_dev_alarm_value REAL,
        minor_dev_alarm_pri INTEGER,
        major_dev_alarm_state TEXT,
        major_dev_alarm_value REAL,
        major_dev_alarm_pri INTEGER,
        dev_target TEXT,
        roc_alarm_state TEXT,
        roc_alarm_value REAL,
        roc_alarm_pri INTEGER,
        roc_time_base TEXT,
        alarm_comment TEXT,
        alarm_ack_model INTEGER,
        lolo_alarm_disable INTEGER,
        lo_alarm_disable INTEGER,
        hi_alarm_disable INTEGER,
        hihi_alarm_disable INTEGER,
        min_dev_alarm_disable INTEGER,
        maj_dev_alarm_disable INTEGER,
        roc_alarm_disable INTEGER,
        lolo_alarm_inhibitor TEXT,
        lo_alarm_inhibitor TEXT,
        hi_alarm_inhibitor TEXT,
        hihi_alarm_inhibitor TEXT,
        min_dev_alarm_inhibitor TEXT,
        maj_dev_alarm_inhibitor TEXT,
        roc_alarm_inhibitor TEXT,
        symbolic_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS alarm_group (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        alarm_group TEXT NOT NULL,
        group_name TEXT,
        comment TEXT,
        event_logged TEXT,
        event_logging_priority INTEGER,
        lolo_alarm_disable INTEGER,
        lo_alarm_disable INTEGER,
        hi_alarm_disable INTEGER,
        hihi_alarm_disable INTEGER,
        min_dev_alarm_disable INTEGER,
        maj_dev_alarm_disable INTEGER,
        roc_alarm_disable INTEGER,
        dsc_alarm_disable INTEGER,
        lolo_alarm_inhibitor TEXT,
        lo_alarm_inhibitor TEXT,
        hi_alarm_inhibitor TEXT,
        hihi_alarm_inhibitor TEXT,
        min_dev_alarm_inhibitor TEXT,
        maj_dev_alarm_inhibitor TEXT,
        roc_alarm_inhibitor TEXT,
        dsc_alarm_inhibitor TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
''')

conn.commit()
conn.close()

print("Database initialized successfully!")